Add callbacks parameter to OperationTrait
zircote/swagger-php pull request #1196
Opened 2022-04-10 02:44 UTC by edipoReboucas

"callbacks" parameter is missiong on OperationTrait.

I implemented this bugfix based on PR https://github.com/zircote/swagger-php/pull/1191.

2022-04-10 22:01 UTC, DerManoMann requested changes
Couple nits but otherwise looking good.
Very happy about the updated tests :)

2022-04-10 22:45 UTC, edipoReboucas commented on src/Attributes/OperationTrait.php
> +     * @param array                     $callbacks
Done

2022-04-10 22:48 UTC, edipoReboucas commented on tests/Analysers/ReflectionAnalyserTest.php
> +
It's a typo, fixed.

2022-04-11 01:32 UTC, DerManoMann approved these changes
Gooking good - thanks.

2022-04-11 01:41 UTC, merged

2022-04-11 01:41 UTC, DerManoMann commented
Thanks @edipoReboucas