Enum can have boolean values
zircote/swagger-php pull request #1467
Opened 2023-08-21 12:59 UTC by momala454

2023-08-21 21:42 UTC, DerManoMann commented
You will need to update the annotation classes too to make the tests pass...

2023-08-22 07:20 UTC, momala454 commented
thanks done

2023-09-01 01:30 UTC, DerManoMann requested changes
One more find/replace that it looks good to go.

2023-09-01 01:30 UTC, DerManoMann commented on src/Annotations/ServerVariable.php
> +     * @var string[]|int[]|float[]|\UnitEnum[]|class-string|bool[]
Ah, just a minor thing, but one I'd like to see changed for consistency - could you move the `bool[]` adjunct to `string`,`int`,`float`, please, so the native types are all together?
 ```suggestion
     * @var string[]|int[]|float[]|bool[]|\UnitEnum[]|class-string
```

2023-09-12 00:18 UTC, DerManoMann approved these changes

2023-09-12 00:18 UTC, merged

2023-09-12 00:18 UTC, DerManoMann commented
Thanks @momala454